services:
  - type: web
    name: kokoheartbot
    env: python
    startCommand: python app.py
    plan: free
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
